spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}   # 기본 dev
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: optional:file:.env[.properties]
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 60MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
            scope: [ profile, email ]
          kakao:
            client-id: ${KAKAO_OAUTH2_CLIENT_ID}
            client-secret: ${KAKAO_OAUTH2_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [ profile_nickname, account_email ]
            client-name: Kakao
          naver:
            client-id: ${NAVER_OAUTH2_CLIENT_ID}
            client-secret: ${NAVER_OAUTH2_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: [ name, email ]
            client-name: Naver
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
server:
  port: ${SERVER_PORT:8080}
usan:
  base-url: ${USAN_BASE_URL}
  bank:
    name: ${USAN_BANK_NAME}
    number: ${USAN_BANK_NUMBER}
    holder: ${USAN_BANK_HOLDER}
  batch:
    excel:
      sheet-name:
      header-rows: 1 #헤더 스킵 개수
      listing-type-col-index: 6 #G 컬럼, 0~6번째 index
      listing-coordinates-col-index: 46 #AU 컬럼, 0~46번째 index
      office-name-col-index: 53 #BB 컬럼, 0~53번째 index
      broker-name-col-index: 54 #BC 컬럼, 0~54번째 index
      address-col-index: 55 #BD 컬럼, 0~55번째 index
      registration-number-col-index: 56 #BE 컬럼, 0~56번째 index
      tel-col-index: 57 #BF 컬럼, 0~57번째 index
      phone-col-index: 58 #BG 컬럼, 0~58번째 index
ncp:
  access-key: ${NCP_ACCESS_KEY}
  secret-key: ${NCP_SECRET_KEY}
  sens:
    service-id: ${NCP_SENS_SERVICE_ID}
    from: ${NCP_SENS_FROM}
naver:
  geocode:
    base-url: https://maps.apigw.ntruss.com
    client-id: ${NAVER_MAP_CLIENT_ID}
    client-secret: ${NAVER_MAP_CLIENT_SECRET}
kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
hecto:
  mcht-id: ${HECTO_MCHT_ID:}
  hash-key: ${HECTO_HASH_KEY:ST1009281328226982205}
  enc-key: ${HECTO_ENC_KEY:pgSettle30y739r82jtd709yOfZ2yK5K}
  test-mode: ${HECTO_TEST_MODE:true}
  mcht-name: ${HECTO_MCHT_NAME:우리동네부동산}
  mcht-ename: ${HECTO_MCHT_ENAME:Usanmap}
file:
  upload-dir: uploads
  public-prefix: /uploads