spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}   # 기본 dev
  jpa:
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${SERVER_PORT:8080}